# Generated by Django 5.1.4 on 2025-01-10 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_order_delivery_date_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
