# Generated by Django 5.1.4 on 2025-01-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
